services:
  postgresql:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data:rw

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - "8081:8080"
    environment:
      KC_THEME_CACHE_ENABLED: "false"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql/keycloak?currentSchema=keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: 'http://localhost:8081'
      KC_PROXY: 'edge'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/keycloak:/opt/keycloak/data
      - ./src/main/java/be/projet3/toutouapp/keycloak_theme/themes/my_custom_theme:/opt/keycloak/themes/my_custom_theme

    depends_on:
      - postgresql