spring:
  application:
    name: ToutouApp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/HappyPaws
          jwk-set-uri: http://localhost:8081/realms/HappyPaws/protocol/openid-connect/certs
